namespace MauiMaterial.Helper;

public static class MaterialColors
{
    // Material 3 color tokens - Light
    public static readonly Color M3PrimaryLight = Color.FromArgb("#6750A4");
    public static readonly Color M3OnPrimaryLight = Color.FromArgb("#FFFFFF");
    public static readonly Color M3PrimaryContainerLight = Color.FromArgb("#EADDFF");
    public static readonly Color M3OnPrimaryContainerLight = Color.FromArgb("#4F378B");
    public static readonly Color M3SecondaryLight = Color.FromArgb("#625B71");
    public static readonly Color M3OnSecondaryLight = Color.FromArgb("#FFFFFF");
    public static readonly Color M3SecondaryContainerLight = Color.FromArgb("#E8DEF8");
    public static readonly Color M3OnSecondaryContainerLight = Color.FromArgb("#4A4458");
    public static readonly Color M3TertiaryLight = Color.FromArgb("#7D5260");
    public static readonly Color M3OnTertiaryLight = Color.FromArgb("#FFFFFF");
    public static readonly Color M3TertiaryContainerLight = Color.FromArgb("#FFD8E4");
    public static readonly Color M3OnTertiaryContainerLight = Color.FromArgb("#633B48");
    public static readonly Color M3ErrorLight = Color.FromArgb("#B3261E");
    public static readonly Color M3OnErrorLight = Color.FromArgb("#FFFFFF");
    public static readonly Color M3ErrorContainerLight = Color.FromArgb("#F9DEDC");
    public static readonly Color M3OnErrorContainerLight = Color.FromArgb("#8C1D18");
    public static readonly Color M3SurfaceLight = Color.FromArgb("#FEF7FF");
    public static readonly Color M3OnSurfaceLight = Color.FromArgb("#1D1B20");
    public static readonly Color M3SurfaceVariantLight = Color.FromArgb("#E7E0EC");
    public static readonly Color M3OnSurfaceVariantLight = Color.FromArgb("#49454F");
    public static readonly Color M3SurfaceContainerHighestLight = Color.FromArgb("#E6E0E9");
    public static readonly Color M3SurfaceContainerHighLight = Color.FromArgb("#ECE6F0");
    public static readonly Color M3SurfaceContainerLight = Color.FromArgb("#F3EDF7");
    public static readonly Color M3SurfaceContainerLowLight = Color.FromArgb("#F7F2FA");
    public static readonly Color M3SurfaceContainerLowestLight = Color.FromArgb("#FFFFFF");
    public static readonly Color M3OutlineLight = Color.FromArgb("#79747E");
    public static readonly Color M3OutlineVariantLight = Color.FromArgb("#CAC4D0");
    public static readonly Color M3ScrimLight = Color.FromArgb("#000000");
    public static readonly Color M3ShadowLight = Color.FromArgb("#000000");
    public static readonly Color M3InverseSurfaceLight = Color.FromArgb("#322F35");
    public static readonly Color M3InverseOnSurfaceLight = Color.FromArgb("#F5EFF7");
    public static readonly Color M3InversePrimaryLight = Color.FromArgb("#D0BCFF");
    public static readonly Color M3SurfaceTintLight = Color.FromArgb("#6750A4");
    public static readonly Color M3BackgroundLight = Color.FromArgb("#FEF7FF");
    public static readonly Color M3OnBackgroundLight = Color.FromArgb("#1D1B20");

    // Material 3 color tokens - Dark
    public static readonly Color M3PrimaryDark = Color.FromArgb("#D0BCFF");
    public static readonly Color M3OnPrimaryDark = Color.FromArgb("#381E72");
    public static readonly Color M3PrimaryContainerDark = Color.FromArgb("#4F378B");
    public static readonly Color M3OnPrimaryContainerDark = Color.FromArgb("#EADDFF");
    public static readonly Color M3SecondaryDark = Color.FromArgb("#CCC2DC");
    public static readonly Color M3OnSecondaryDark = Color.FromArgb("#332D41");
    public static readonly Color M3SecondaryContainerDark = Color.FromArgb("#4A4458");
    public static readonly Color M3OnSecondaryContainerDark = Color.FromArgb("#E8DEF8");
    public static readonly Color M3TertiaryDark = Color.FromArgb("#EFB8C8");
    public static readonly Color M3OnTertiaryDark = Color.FromArgb("#492532");
    public static readonly Color M3TertiaryContainerDark = Color.FromArgb("#633B48");
    public static readonly Color M3OnTertiaryContainerDark = Color.FromArgb("#FFD8E4");
    public static readonly Color M3ErrorDark = Color.FromArgb("#F2B8B5");
    public static readonly Color M3OnErrorDark = Color.FromArgb("#601410");
    public static readonly Color M3ErrorContainerDark = Color.FromArgb("#8C1D18");
    public static readonly Color M3OnErrorContainerDark = Color.FromArgb("#F9DEDC");
    public static readonly Color M3SurfaceDark = Color.FromArgb("#141218");
    public static readonly Color M3OnSurfaceDark = Color.FromArgb("#E6E0E9");
    public static readonly Color M3SurfaceVariantDark = Color.FromArgb("#49454F");
    public static readonly Color M3OnSurfaceVariantDark = Color.FromArgb("#CAC4D0");
    public static readonly Color M3SurfaceContainerHighestDark = Color.FromArgb("#36343B");
    public static readonly Color M3SurfaceContainerHighDark = Color.FromArgb("#2B2930");
    public static readonly Color M3SurfaceContainerDark = Color.FromArgb("#211F26");
    public static readonly Color M3SurfaceContainerLowDark = Color.FromArgb("#1D1B20");
    public static readonly Color M3SurfaceContainerLowestDark = Color.FromArgb("#0F0D13");
    public static readonly Color M3OutlineDark = Color.FromArgb("#938F99");
    public static readonly Color M3OutlineVariantDark = Color.FromArgb("#49454F");
    public static readonly Color M3ScrimDark = Color.FromArgb("#000000");
    public static readonly Color M3ShadowDark = Color.FromArgb("#000000");
    public static readonly Color M3InverseSurfaceDark = Color.FromArgb("#E6E0E9");
    public static readonly Color M3InverseOnSurfaceDark = Color.FromArgb("#322F35");
    public static readonly Color M3InversePrimaryDark = Color.FromArgb("#6750A4");
    public static readonly Color M3SurfaceTintDark = Color.FromArgb("#D0BCFF");
    public static readonly Color M3BackgroundDark = Color.FromArgb("#141218");
    public static readonly Color M3OnBackgroundDark = Color.FromArgb("#E6E0E9");
}
